# Generated by Django 4.2.3 on 2024-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
    ]
