# Generated by Django 4.2.3 on 2024-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_remove_file_pdf_file_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
