# Generated by Django 4.2.3 on 2024-05-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
