# Generated by Django 4.2.3 on 2024-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_alter_file_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
