# Generated by Django 4.2.3 on 2024-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_file_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='himage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
